### ISSUE TITLE
Feature request: Icon stamp for unread count

### ISSUE THREAD

**Issue by geolessel** [danielma/Resolutions.app#9]
Like

![screenshot 2017-01-03 11 34 01](https://cloud.githubusercontent.com/assets/385726/21620307/89bc6af6-d1a8-11e6-8403-a27b639d67d1.png)

**Comment by mcfadden** [comment]
Please have an option to _not_ show the badge too. 😁

Bonus points for showing the badge on a per-repo basis.

**Comment by shanebonham** [comment]
Tying it into the macOS notifications system might be nice, so that you have these prefs:

![image](https://cloud.githubusercontent.com/assets/423741/21623165/fab636bc-d1b5-11e6-947f-af63f59132da.png)

**Comment by danielma** [comment]
Feature added in #22
